@startuml
Class Usuario{
    +Ingresar()
}

Class Foto{
    +Ingresar()
    +Cancelar()
}

Class Programa{
    +lista:List[foto]
    +Clasificar(Planta)
    +Cancelar()
}

Class Planta{
    +color_petalo:str
    +largo_petalo:str
    +color_tallo:str
    +largo_tallo:str
    +color:str
    +nombre_planta:str
    +color_hojas:str
    +fruto:str
    +describir():str
}

Class Historial{
    +nombre_planta:str
    +fotos:list[Foto]
}

Usuario"1" -- Foto:se ingresa en
Planta -- Programa
Programa"1..*" *-- "1"Foto
Historial *-- Planta:se guarda en
Usuario --* Historial:tiene acceso

@enduml
